// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRFMltR1ljwEVgyrm8OAY_lTXw_jmpu6s',
    appId: '1:486531732561:web:37755b0ad43c5f7b615470',
    messagingSenderId: '486531732561',
    projectId: 'studentology-59005',
    authDomain: 'studentology-59005.firebaseapp.com',
    storageBucket: 'studentology-59005.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS979AhXH2ggtMdTahoyVd2FjNWLa8OA4',
    appId: '1:486531732561:android:ac8face3acccc323615470',
    messagingSenderId: '486531732561',
    projectId: 'studentology-59005',
    storageBucket: 'studentology-59005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB8RdRWuaThIeo_Y-aGOIzQMvt3NGlXe0',
    appId: '1:486531732561:ios:391e9ebecdb85bc6615470',
    messagingSenderId: '486531732561',
    projectId: 'studentology-59005',
    storageBucket: 'studentology-59005.firebasestorage.app',
    iosBundleId: 'com.example.studentology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB8RdRWuaThIeo_Y-aGOIzQMvt3NGlXe0',
    appId: '1:486531732561:ios:391e9ebecdb85bc6615470',
    messagingSenderId: '486531732561',
    projectId: 'studentology-59005',
    storageBucket: 'studentology-59005.firebasestorage.app',
    iosBundleId: 'com.example.studentology',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRFMltR1ljwEVgyrm8OAY_lTXw_jmpu6s',
    appId: '1:486531732561:web:411446aae975a55e615470',
    messagingSenderId: '486531732561',
    projectId: 'studentology-59005',
    authDomain: 'studentology-59005.firebaseapp.com',
    storageBucket: 'studentology-59005.firebasestorage.app',
  );
}