import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';

import 'package:studentology/core/theme/app_theme.dart';
// firebase_options.dart is generated by running:
//   flutterfire configure
// from the project root after installing the FlutterFire CLI.
import 'package:studentology/firebase_options.dart';
import 'package:studentology/providers/auth_provider.dart';
import 'package:studentology/providers/exam_provider.dart';
import 'package:studentology/providers/grade_provider.dart';
import 'package:studentology/providers/schedule_provider.dart';
import 'package:studentology/providers/subject_provider.dart';
import 'package:studentology/providers/task_provider.dart';
import 'package:studentology/providers/theme_provider.dart';
import 'package:studentology/providers/timer_provider.dart';
import 'package:studentology/services/notification_service.dart';
import 'package:studentology/core/navigation/slide_route.dart';
import 'package:studentology/screens/auth/login_screen.dart';
import 'package:studentology/screens/auth/register_screen.dart';
import 'package:studentology/screens/exams/exams_screen.dart';
import 'package:studentology/screens/grades/grades_screen.dart';
import 'package:studentology/screens/home/home_screen.dart';
import 'package:studentology/screens/profile/profile_screen.dart';
import 'package:studentology/screens/splash_screen.dart';
import 'package:studentology/screens/tasks/tasks_screen.dart';
import 'package:studentology/screens/thesis/thesis_screen.dart';
import 'package:studentology/screens/timetable/timetable_screen.dart';
import 'package:studentology/screens/timer/timer_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  Object? firebaseError;
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    firebaseError = e;
  }

  if (firebaseError != null) {
    runApp(_FirebaseErrorApp(firebaseError.toString()));
    return;
  }

  await NotificationService.initialize();

  // Lock to portrait — a student planner doesn't benefit from landscape.
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Transparent status + navigation bars so the app background bleeds through.
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarIconBrightness: Brightness.light,
    ),
  );

  runApp(const StudentologyApp());
}

class _FirebaseErrorApp extends StatelessWidget {
  final String message;

  const _FirebaseErrorApp(this.message);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: const Color(0xFF0D1117),
        body: SafeArea(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Icon(
                  Icons.error_outline_rounded,
                  color: Color(0xFFEF5350),
                  size: 64,
                ),
                const SizedBox(height: 24),
                const Text(
                  'Firebase failed to initialize',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontWeight: FontWeight.w700,
                  ),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 12),
                Text(
                  message,
                  style: const TextStyle(
                    color: Color(0xFF8B9CB3),
                    fontSize: 13,
                  ),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 32),
                const Text(
                  'Check that google-services.json (Android) or\n'
                  'GoogleService-Info.plist (iOS) is in place,\n'
                  'then restart the app.',
                  style: TextStyle(
                    color: Color(0xFF5A6A7E),
                    fontSize: 12,
                  ),
                  textAlign: TextAlign.center,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

// ── Root widget ────────────────────────────────────────────────────────────

class StudentologyApp extends StatelessWidget {
  const StudentologyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // ThemeProvider is first so every other provider can read theme state.
        ChangeNotifierProvider(create: (_) => ThemeProvider()),

        // AuthProvider listens to Firebase authStateChanges immediately on creation.
        ChangeNotifierProvider(create: (_) => AuthProvider()),

        // Data providers are initialised with a userId by each screen after sign-in.
        ChangeNotifierProvider(create: (_) => SubjectProvider()),
        ChangeNotifierProvider(create: (_) => ScheduleProvider()),
        ChangeNotifierProvider(create: (_) => TaskProvider()),
        ChangeNotifierProvider(create: (_) => ExamProvider()),
        ChangeNotifierProvider(create: (_) => GradeProvider()),

        // TimerProvider is fully self-contained — no userId needed.
        ChangeNotifierProvider(create: (_) => TimerProvider()),
      ],
      child: Consumer<ThemeProvider>(
        builder: (_, themeProvider, _) {
          return MaterialApp(
            title: 'Studentology',
            debugShowCheckedModeBanner: false,
            theme: AppTheme.lightTheme,
            darkTheme: AppTheme.darkTheme,
            themeMode: themeProvider.themeMode,
            // SplashScreen owns the initial navigation decision.
            home: const SplashScreen(),
            // All named-route navigations use the slide + fade transition.
            onGenerateRoute: (settings) {
              Widget? page;
              switch (settings.name) {
                case '/login':
                  page = const LoginScreen();
                case '/register':
                  page = const RegisterScreen();
                case '/home':
                  page = const HomeScreen();
                case '/timetable':
                  page = const TimetableScreen();
                case '/tasks':
                  page = const TasksScreen();
                case '/exams':
                  page = const ExamsScreen();
                case '/timer':
                  page = const TimerScreen();
                case '/grades':
                  page = const GradesScreen();
                case '/thesis':
                  page = const ThesisScreen();
                case '/profile':
                  page = const ProfileScreen();
              }
              if (page != null) return slideRoute(page, settings: settings);
              return null;
            },
          );
        },
      ),
    );
  }
}

